FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /app

RUN dotnet new console -n producer
WORKDIR /app/producer

RUN dotnet add package Confluent.Kafka

COPY producer/Program.cs ./

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/producer/out ./

ENTRYPOINT ["dotnet", "producer.dll"]
